// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVN0Ii7C8xMbCKqnXJoNCpNU_77e7ItY0',
    appId: '1:193845498725:android:b9c67183c9e73ffb92c78c',
    messagingSenderId: '193845498725',
    projectId: 'nfc-setup',
    databaseURL: 'https://nfc-setup-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nfc-setup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOOrx27PsazE8dUJpEqzvAr0780w9CCP4',
    appId: '1:193845498725:ios:e6b87b5c6c1284c392c78c',
    messagingSenderId: '193845498725',
    projectId: 'nfc-setup',
    databaseURL: 'https://nfc-setup-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nfc-setup.firebasestorage.app',
    iosBundleId: 'com.example.nfcApp',
  );
}
